### ISSUE TITLE
Multiple {{download_link::*}}

### ISSUE THREAD

**Issue by ngdot** [heimrichhannot/contao-inserttagcollection-bundle#1]
Contao: 4.9.11

If I use `{{download_link}}` multiple on the same site, for example in an ce_text element, only the first link works correct. All other links produce a 404 with the follwing error: `Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Invalid file name" `

Also all `cid` params are also empty. I don't know if this is correct, but it doesn't feel so :P

**Comment by koertho** [comment]
Hi, I couldn't reproduce this problem. Do you have cache active? Maybe you need to append the uncached flag? If this does not help, could you provide an error stack trace (for example an screenshot of the error in dev mode)?

**Comment by ngdot** [comment]
The cache on this site is deactivated, I also tested the uncached flag, doesn't help.

![screenshot-swbr-2021 01 27-15_42_04](https://user-images.githubusercontent.com/8327905/106007742-e8253900-60b6-11eb-94b3-b6fc7b3b8f50.png)

**Comment by koertho** [comment]
Thanks, unfortunately the log not really helps for debugging an possible error. Indeed it looks like the file name has invalid characters.

**Comment by koertho** [comment]
Please test it with the file renamed to snake_case.

**Comment by ngdot** [comment]
Same Problem, already tested a lot of combinations :(
I'am running the site on nginx, maybe thats a problem?
But I don't get, why the first works well, and second wont work…

Files are stored unter `files/downloads/test/2017`

![Bildschirmfoto 2021-01-28 um 12 40 21](https://user-images.githubusercontent.com/8327905/106134044-507f2380-6166-11eb-96b5-2b11fb374707.jpg)

![Bildschirmfoto 2021-01-28 um 12 40 47](https://user-images.githubusercontent.com/8327905/106134033-4e1cc980-6166-11eb-8ab9-7bd894497910.jpg)

![Bildschirmfoto 2021-01-28 um 12 44 52](https://user-images.githubusercontent.com/8327905/106134352-b2d82400-6166-11eb-9002-e8bcb1aa901e.jpg)

**Comment by koertho** [comment]
Ok, thanks. Next step would be reproduce the error in an clean contao install to check if no other extension is the reason. For me the link looks correct and this is everything the inserttag does. What happens afterwards has nothing to do with this extension.

**Comment by ngdot** [comment]
Okay, thanks – I will make some tests.

**Comment by ngdot** [comment]
Tested it on a fresh contao 4.9.11, same problem.
Tested also apache & nginx and php 7 and 8, still the same problem.
Normal contao download element(s) work fine and `cid` is filled correctly.
What I really don't understand, is the fact that the first download works, but all others not – that makes no sense for me. But I think the main problem is, that the `cid` param is not filled.

**Comment by koertho** [comment]
I found the error and indeed it was the cid parameter. Will be fixed in next release. Thanks for reporting!
