### ISSUE TITLE
Inserttag: download_link and download_size didn't work anymore

### ISSUE THREAD

**Issue by Ainschy** [heimrichhannot/contao-inserttagcollection-bundle#5]
**Context**
Contao version: 4.9.24
Bundle version: 1.2
PHP version: 7.4

**Description**
Using inserttag like `{{download::XYZ}}` works perfect as normal, `{{download_link::XYZ}}` and `{{download_size::XYZ}}` didn't have access to the rendering template vars, so there are empty

**Comment by Ainschy** [comment]
Its a bug in Contao 4.9.24 see https://github.com/contao/contao/issues/3894

**Comment by Ainschy** [comment]
The bug affects these functions 

https://github.com/heimrichhannot/contao-inserttagcollection-bundle/blob/778135c7373ef762dcfa9a802826c93ddf21dd22/src/EventListener/InserttagListener.php#L142-L157

**Comment by Ainschy** [comment]
Contao BC Break

**Comment by koertho** [comment]
@Ainschy Thanks for reporting back! I hadn't the time to look into this issue. So it someone is reading here, a workaround is skipping version 4.9.24 and 4.9.25 and stay at version 4.9.23. I hope a future version fixes this problem.
